const KNOWLEDGE_BASE_PATH = "./dataInjest/amazon"; 
const KNOWLEDGE_BASE_DB_COLLECTION_NAME = "amazon-knowledge-base-3";

export {
    KNOWLEDGE_BASE_DIR,
    KNOWLEDGE_BASE_REPO_URL,
    KNOWLEDGE_BASE_PATH,
    KNOWLEDGE_BASE_DB_COLLECTION_NAME
  };
